export const GAME_CONFIG = {
  TOTAL_HORSES: 20,
  HORSES_PER_ROUND: 10,
  TOTAL_ROUNDS: 6,
  MIN_CONDITION: 1,
  MAX_CONDITION: 100,
  ROUND_DELAY_MS: 500,
  ANIMATION_RESET_DELAY_MS: 100,
  DOM_UPDATE_DELAY_MS: 50,
} as const

export const RACE_TIMING = {
  BASE_SPEED_MPS: 10,
  MIN_RACE_DURATION_MS: 2000,
  DISTANCE_TO_DURATION_FACTOR: 2,
  ANIMATION_SPEED_MULTIPLIER: 100,
} as const
